runtime: nodejs18

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*\.(json|ico|js|png|txt|svg|woff|woff2|ttf|map|jpg|jpeg|gif|bmp|png|webp|css))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|txt|svg|woff|woff2|ttf|map|jpg|jpeg|gif|bmp|png|webp|css)$

  - url: /static
    static_dir: build/static

  - url: /.*
    static_files: build/index.html
    upload: build/index.html