// SIGN IN
export const SIGNIN_REQUEST_START = "SIGNIN_REQUEST_START";
export const SIGNIN_REQUEST_SUCCESS = "SIGNIN_REQUEST_SUCCESS";
export const SIGNIN_REQUEST_FAILURE = "SIGNIN_REQUEST_FAILURE";
export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";

// SERVICES
export const GET_SERVICES_START = "GET_SERVICES_START";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";

// PACKAGES
export const GET_PACKAGES_START = "GET_PACKAGES_START";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAILURE = "GET_PACKAGES_FAILURE";

// DATES
export const GET_DATES_START = "GET_DATES_START";
export const GET_DATES_SUCCESS = "GET_DATES_SUCCESS";
export const GET_DATES_FAILURE = "GET_DATES_FAILURE";

// BARBER
export const GET_BARBERS_START = "GET_BARBERS_START";
export const GET_BARBERS_SUCCESS = "GET_BARBERS_SUCCESS";
export const GET_BARBERS_FAILURE = "GET_BARBERS_FAILURE";

// SLOTS
export const GET_AVAILABLE_TIME_SLOT_START = "GET_AVAILABLE_TIME_SLOT_START";
export const GET_AVAILABLE_TIME_SLOT_SUCCESS = "GET_AVAILABLE_TIME_SLOT_SUCCESS";
export const GET_AVAILABLE_TIME_SLOT_FAILURE = "GET_AVAILABLE_TIME_SLOT_FAILURE";